// <auto-generated />
using Demo1.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo1.Migrations
{
    [DbContext(typeof(MyMainContext))]
    [Migration("20260507112436_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("Demo1.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Description = "The city that never sleeps",
                            Name = "New York",
                            Population = 8419600
                        },
                        new
                        {
                            Id = 2,
                            Country = "France",
                            Description = "The city of love",
                            Name = "Paris",
                            Population = 2148000
                        },
                        new
                        {
                            Id = 3,
                            Country = "Japan",
                            Description = "The city of the rising sun",
                            Name = "Tokyo",
                            Population = 13929000
                        });
                });

            modelBuilder.Entity("Demo1.Entities.LandMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("LandMarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A colossal neoclassical sculpture on Liberty Island in New York Harbor.",
                            IsNice = false,
                            Name = "Statue of Liberty"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "A 102-story Art Deco skyscraper in Midtown Manhattan, New York City.",
                            IsNice = false,
                            Name = "Empire State Building"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "A wrought-iron lattice tower on the Champ de Mars in Paris, France.",
                            IsNice = false,
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "The world's largest art museum and a historic monument in Paris, France.",
                            IsNice = false,
                            Name = "Louvre Museum"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "A communications and observation tower in the Shiba-koen district of Minato, Tokyo, Japan.",
                            IsNice = false,
                            Name = "Tokyo Tower"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "An ancient Buddhist temple located in Asakusa, Tokyo, Japan.",
                            IsNice = false,
                            Name = "Senso-ji Temple"
                        });
                });

            modelBuilder.Entity("Demo1.Entities.LandMark", b =>
                {
                    b.HasOne("Demo1.Entities.City", "City")
                        .WithMany("LandMarks")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Demo1.Entities.City", b =>
                {
                    b.Navigation("LandMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
